[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[dependencies]
forge-std = "^1.8.2"
openzeppelin-contracts = "^5.0.2"

[rpc_endpoints]
base_mainnet = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base_mainnet = { key = "${BASE_ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASE_ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
